Don't use export FOO=bar syntax in runtests.sh
Solaris' shell can't run those. We can actually remove the variables
altogether since the tester/barnowl wrapper will take care of it. Also
make the error message in the latter more accurate.

diff --git a/barnowl b/barnowl
--- a/barnowl
+++ b/barnowl
@@ -7,7 +7,7 @@ SRCDIR=`dirname "${0}"`
 EXE="$0.bin"
 
 if test ! -x "$EXE"; then
-    echo "Cannot find barnowl.bin" >&2
+    echo "Cannot find $EXE" >&2
     exit 1
 fi
 
