do-release: Support --no-tag for test builds.

diff --git a/scripts/do-release b/scripts/do-release
--- a/scripts/do-release
+++ b/scripts/do-release
@@ -6,10 +6,14 @@ die() {
 }
 
 force=
+no_tag=
 
-if [ "$1" = "-f" ]; then
-    force=1
-fi
+for arg; do
+    case $arg in
+        -f) force=1 ;;
+        --no-tag) no_tag=1 ;;
+    esac
+done
 
 VERS=$(perl -ne 'print $1 if m{^AC_INIT\(\[[^\]]+\],\s*\[([^\]]+)\]}' configure.ac) \
     || die "Unable to parse barnowl version"
@@ -20,15 +24,19 @@ if [ ! "$force" ] && [ "$VERS" != "$(head -1 ChangeLog)" ]; then
     die "No ChangeLog entry for version $VERS, aborting."
 fi
 
-if git cat-file -t "$TAG" > /dev/null 2>&1; then
-    die "Error: Object $TAG already exists."
+if ! [ "$no_tag" ]; then
+    if git cat-file -t "$TAG" > /dev/null 2>&1; then
+        die "Error: Object $TAG already exists."
+    fi
+
+    git tag -s -m "BarnOwl $VERS" "$TAG"
+else
+    TAG=HEAD
 fi
 
 exittrap() { :; }
 for sig in 1 2 13 15; do trap "exit $(($sig + 128))" $sig; done
 trap 'exittrap' EXIT
-
-git tag -s -m "BarnOwl $VERS" "$TAG"
 
 TMPDIR=$(mktemp -d /tmp/barnowl.XXXXXX)
 
