Add usage and clean up the build script a lot.

diff --git a/scripts/locker-build b/scripts/locker-build
--- a/scripts/locker-build
+++ b/scripts/locker-build
@@ -1,23 +1,56 @@
-#!/bin/bash
+#!/bin/sh
+
+#########################################################
+# Build script to build BarnOwl for the locker.
+
+# Usage: locker-build [-n] [-o OUTPUT-TGZ] VERSION SOURCE-TARBALL
+# -n is a dry-run, and drops to a shell in the build directory
+# -o does the install into a temporary directory and tars it into the
+#    specified tarball instead.
+# SOURCE-TARBALL is a source tarball, created by do-release
+# VERSION should be of the form 'barnowl-VERSION'
+#
+# TODO: Scrape $VERSION from the tarball
 
 die() {
-      echo "$1" 2>&1;
-      if [ ! -z "$TMPDIR" ]
-      then
-          echo "The failed build can be found in $TMPDIR"
-      fi
-      exit -1
+      echo "$@" 2>&1;
+      exit 1;
 }
 
+usage () {
+    echo "Usage: $0 [-n] [-o OUTPUT-TGZ] VERSION SOURCE-TARBALL"
+    exit 2;
+}
+
+exittrap() { :; }
+for sig in 1 2 13 15; do trap "exit $(($sig + 128))" $sig; done
+trap 'exittrap' EXIT
+
+SRC_TGZ=
+OUT_TGZ=
 DRYRUN=
-if [ "$1" = "-n" ]; then
-    DRYRUN=1
-    shift;
-fi
+
+set -- `getopt no: "$@"`
+[ $? -eq 0 ] || usage
+
+for opt
+do
+    case "$opt" in
+        -n)
+            DRYRUN=1; shift ;;
+        -o)
+            OUT_TGZ="$2"; shift 2;;
+        --)
+            shift; break ;;
+    esac
+done
 
 NAME="$1"
-NAME="${NAME:?Usage: barnowl-locker-build NAME}"
-TGZ="$2"
+SRC_TGZ="$2"
+
+test -z "$NAME" && usage
+test -z "$SRC_TGZ"  && usage
+
 
 ATHENA_SYS="${ATHENA_SYS:-$(machtype -S)}"
 
@@ -32,58 +65,50 @@ fi
 attach barnowl
 aklog
 
-mkdir -p /tmp/barnowl.$UID || die "Unable to mkdir"
-TMPDIR=$(mktemp -d /tmp/barnowl.$UID/buildXXXXXX) || die "Unable to mktemp"
-cd "$TMPDIR"                         || die "Unable to cd to $TMPDIR"
+TMPDIR=$(mktemp -d /tmp/barnowl-build-XXXXXX) || die "Unable to mktemp"
 
-$TAR xzvf "$BARNOWL_TGZ" || die "Unable to untar"
-cd *;
+exittrap() { rm -rf "$TMPDIR"; }
 
-# git archive --remote="$REPOURL" --format=tar $BRANCH | $TAR xf - || die "Unable to create archive"
-# svn co file:///mit/barnowl/src/svn/$REPOPATH/owl/ barnowl || die "Unable to checkout"
-# cd barnowl                           || die "Unable to cd"
+$TAR -C "$TMPDIR" -xzvf "$SRC_TGZ" || die "Unable to untar"
 
-ARGS=
+(
+    cd "$TMPDIR"/* || die "Unable to cd to $TMPDIR"
 
-# if ! grep -i debian /etc/athena/version >/dev/null 2>&1 ; then
-#     ARGS=--enable-athstatic
-# fi
+    BARNOWL="/afs/sipb.mit.edu/project/barnowl/arch/$ATHENA_SYS"
+    export PKG_CONFIG_PATH="$BARNOWL/lib/pkgconfig"
 
-# autoreconf         || die "autoreconf failed"
-# autoconf        || die "autoconf failed"
+    CFLAGS="-I$BARNOWL/include" \
+        LDFLAGS="-L$BARNOWL/lib -Wl,-R$BARNOWL/lib" \
+        ./configure --exec-prefix="/mit/barnowl/arch/$ATHENA_SYS" \
+        --prefix="/mit/barnowl/builds/$NAME" --mandir=/mit/barnowl/man \
+        PROTECT_CFLAGS=-fno-stack-protector \
+        || die "configure failed"
 
-BARNOWL="/afs/sipb.mit.edu/project/barnowl/arch/$ATHENA_SYS"
-export PKG_CONFIG_PATH="$BARNOWL/lib/pkgconfig"
+    $MAKE clean  || die "make clean failed"
 
-CFLAGS="-I$BARNOWL/include" \
-LDFLAGS="-L$BARNOWL/lib -Wl,-R$BARNOWL/lib" \
-./configure --exec-prefix="/mit/barnowl/arch/$ATHENA_SYS" \
-            --prefix="/mit/barnowl/builds/$NAME" --mandir=/mit/barnowl/man \
-            PROTECT_CFLAGS=-fno-stack-protector \
-            $ARGS \
-            || die "configure failed"
-
-$MAKE clean  || die "make clean failed"
-
-CPUS=$(athinfo localhost cpuspeed | grep -c MHz)
-if [ "$CPUS" = 0 ]; then
-   CPUS=1
-fi
-
-$MAKE -j$CPUS EXE=$NAME all || die "make failed"
-
-if [ -n "$DRYRUN" ]; then
-    echo "Build completed; Dropping to a shell..."
-    exec $SHELL;
-else
-    if [ -n "$TGZ" ]; then
-        mkdir tgz
-        $MAKE EXE=$NAME DESTDIR=tgz install || die "Install failed"
-        cd tgz && $TAR czvf "$TGZ" . || die "Make tarball failed"
-    else
-        $MAKE EXE=$NAME install || die "Install failed"
+    CPUS=$(athinfo localhost cpuspeed | grep -c MHz)
+    if [ "$CPUS" = 0 ]; then
+        CPUS=1
     fi
+
+    $MAKE -j$CPUS EXE=$NAME all || die "make failed"
+
+    if [ -n "$DRYRUN" ]; then
+        echo "Build completed; Dropping to a shell..."
+        $SHELL
+    else
+        if [ -n "$OUT_TGZ" ]; then
+            mkdir tgz
+            $MAKE EXE=$NAME DESTDIR=tgz install || die "Install failed"
+        else
+            $MAKE EXE=$NAME install || die "Install failed"
+        fi
+    fi
+)
+
+if [ -n "$OUT_TGZ" ]; then
+    $TAR -C "$TMPDIR/"*/tgz -czvf "$OUT_TGZ" . || die "Make tarball failed"
 fi
 
-cd /tmp
 rm -rf "$TMPDIR"
+exittrap() { :; }
