scripts/locker-build: use --program-suffix instead of EXE
Update our build script to use the new --program-suffix option to set the
installed binary name to "barnowl-$VERSION", instead of setting the
Makefile variable EXE. At the same time, update it to automatically
detect the version from owl.h, instead of taking it as an argument.

diff --git a/scripts/locker-build b/scripts/locker-build
--- a/scripts/locker-build
+++ b/scripts/locker-build
@@ -3,14 +3,11 @@
 #########################################################
 # Build script to build BarnOwl for the locker.
 
-# Usage: locker-build [-n] [-o OUTPUT-TGZ] VERSION SOURCE-TARBALL
+# Usage: locker-build [-n] [-o OUTPUT-TGZ] SOURCE-TARBALL
 # -n is a dry-run, and drops to a shell in the build directory
 # -o does the install into a temporary directory and tars it into the
 #    specified tarball instead.
 # SOURCE-TARBALL is a source tarball, created by do-release
-# VERSION should be of the form 'barnowl-VERSION'
-#
-# TODO: Scrape $VERSION from the tarball
 
 die() {
     echo "$@" 2>&1;
@@ -24,7 +21,7 @@ die() {
 }
 
 usage () {
-    echo "Usage: $0 [-n] [-o OUTPUT-TGZ] VERSION SOURCE-TARBALL"
+    echo "Usage: $0 [-n] [-o OUTPUT-TGZ] SOURCE-TARBALL"
     exit 2;
 }
 
@@ -51,10 +48,8 @@ do
     esac
 done
 
-NAME="$1"
-SRC_TGZ="$2"
+SRC_TGZ="$1"
 
-test -z "$NAME" && usage
 test -z "$SRC_TGZ"  && usage
 
 
@@ -79,6 +74,10 @@ $TAR -C "$TMPDIR" -xzf "$SRC_TGZ" || die "Unable to untar"
 
 (
     cd "$TMPDIR"/* || die "Unable to cd to $TMPDIR"
+    VERS=$(perl -ne 'print $1 if m{^#define\s*OWL_VERSION_STRING\s*"([^"]+)"}' owl.h)
+    test -z "$VERS" && die "Unable to detect barnowl version."
+
+    echo "Building BarnOwl version $VERS"
 
     BARNOWL="/afs/sipb.mit.edu/project/barnowl/arch/$ATHENA_SYS"
     export PKG_CONFIG_PATH="$BARNOWL/lib/pkgconfig"
@@ -86,7 +85,8 @@ $TAR -C "$TMPDIR" -xzf "$SRC_TGZ" || die "Unable to untar"
     CFLAGS="-I$BARNOWL/include" \
         LDFLAGS="-L$BARNOWL/lib -Wl,-R$BARNOWL/lib" \
         ./configure --exec-prefix="/mit/barnowl/arch/$ATHENA_SYS" \
-        --prefix="/mit/barnowl/builds/$NAME" --mandir=/mit/barnowl/man \
+        --prefix="/mit/barnowl/builds/barnowl-$VERS" --mandir=/mit/barnowl/man \
+        --program-suffix="-$VERS" \
         PROTECT_CFLAGS=-fno-stack-protector \
         || die "configure failed"
 
@@ -97,7 +97,7 @@ $TAR -C "$TMPDIR" -xzf "$SRC_TGZ" || die "Unable to untar"
         CPUS=1
     fi
 
-    $MAKE -j$CPUS EXE=$NAME all || die "make failed"
+    $MAKE -j$CPUS all || die "make failed"
 
     if [ -n "$DRYRUN" ]; then
         echo "Build completed; Dropping to a shell..."
@@ -105,9 +105,9 @@ $TAR -C "$TMPDIR" -xzf "$SRC_TGZ" || die "Unable to untar"
     else
         if [ -n "$OUT_TGZ" ]; then
             mkdir tgz
-            $MAKE EXE=$NAME DESTDIR=tgz install || die "Install failed"
+            $MAKE DESTDIR=tgz install || die "Install failed"
         else
-            $MAKE EXE=$NAME install || die "Install failed"
+            $MAKE install || die "Install failed"
         fi
     fi
 )
